### ISSUE TITLE
Обновления в верстке

### ISSUE THREAD

**Issue by 333hronos** [neko-natum/DTF-dark-themes#2]
Привет, с недавними правками сайта белый кусочек в оформлении вылез:
![изображение](https://user-images.githubusercontent.com/67212103/121382611-735ce800-c94f-11eb-9ea8-7a2f4d0c6e98.png)

И еще можно ли убрать обводки-границы вокруг постов из соц. сетей, и ленты комментариев, для чистоты интерфейса?
![изображение](https://user-images.githubusercontent.com/67212103/121383209-f41be400-c94f-11eb-82a8-c759d1aa42a3.png)
И у кнопки ленты комментариев, сверху-справа , убрать фон и сдвинуть её левее, в одну линию с комментариями.

Получится примерно так:
![изображение](https://user-images.githubusercontent.com/67212103/121385374-ba4bdd00-c951-11eb-913f-6114d4f57235.png)
Обрати внимание, насколько чище и аккуратнее стало оформление без границ.

p.s. Так как вкладки "Discussions" тут почему-то нет, то запощу здесь.

p.p.s. Спасибо за твои старания.

**Comment by neko-natum** [comment]
Да, эти места доработаю. К сожалению смогу исправить только ближе к концу июня.

**Comment by 333hronos** [comment]
Я сделяль
![изображение](https://user-images.githubusercontent.com/67212103/121418990-29d2c400-c974-11eb-9bd2-a8890815781e.png)

Ну, кроме кнопки ленты комментариев, сверху-справа – не нашел как убрать у неё серый фон, отдельно от фона центра страницы

@-moz-document url-prefix("https://dtf.ru/") {

### /* Акцентные цвета, в фирменных цветах DTF */
:root {
	--site_specific_1: `#a3daee!important;`
	--site_specific_2: `#a3daee;`
}

### /* Цвет лого, в фирменном цветах DTF */
.entry_header__archive .icon, .error__ico, .comments_updates .icon, .search_bar__button .icon, .icon--site_logo, .chat__header-back svg g path, .v-list-tab__icon svg {
	fill: `#a3daee !important;`
}

### /* Убрать границу у комментов в ленте */
.live__item--comment {
	--gap: 12px;
	--offset-x: 13px;
	--offset-top: 8px;
	--offset-bottom: 6px;
	--color-background: transparent;
	--color-border: transparent;
	margin-left: 16px;
	margin-top: 0;
	margin-bottom: var(--gap);
	padding: var(--offset-top) var(--offset-x) var(--offset-bottom);
	border-radius: 8px;
	border: `0px` solid var(--color-border);
	background-color: var(--color-background);
}

### /* Убрать границу вокруг постов из соц. сетей, и немного закруглить края постов */
.andropov_telegram, .andropov_tweet {
	display: -ms-flexbox;
	display: flex;
	-ms-flex-direction: column;
	flex-direction: column;
	border: `0px` solid #dedede;
	border-radius: `5px;`
	background-color: #fff;
}

### /* Затемнить обновленный блок снизу-слева, и отключить эффект его выпрыгивания */
.sidebar__footer[data-v-48f6e1e3] {
	color: rgba(0,0,0,0.75);
	font-size: 14px;
	line-height: 20px;
	padding-top: 5px;
	padding-bottom: 14px;
	background-color: `#1b1b1b;`
	-webkit-transition:  `none;`
	transition:  `none;`
}
.sidebar__footer[data-v-48f6e1e3]::before {
	content: '';
	position: absolute;
	left: 0;
	top: -15px;
	width: 100%;
	height: 15px;
	background-color: `#1b1b1b;`
}
.sidebar__footer[data-v-48f6e1e3]::before {
	content: '';
	position: absolute;
	left: 0;
	top: -15px;
	width: 100%;
	height: 15px;
	background-image: `url("")!important;`
}

### /* Коррекция под темную тему элементов написания новой записи в профиле */
Было:
![изображение](https://user-images.githubusercontent.com/67212103/121443439-2819f800-c996-11eb-8034-b9d11170e1ba.png)
Стало:
![изображение](https://user-images.githubusercontent.com/67212103/121443528-513a8880-c996-11eb-900e-79519b6667d0.png)

.mini-editor__button {
	--height: 30px;
	--background-color: `#000`;
	height: var(--height);
	border-radius: var(--height);
	padding-left: 10px;
	padding-right: 12px;
	display: -ms-flexbox;
	display: flex;
	-ms-flex-align: baseline;
	align-items: baseline;
	cursor: pointer;
	background-color: var(--background-color);
	color: `#a3daee;`
	font-size: 14px;
	line-height: calc(var(--height) + 1px);
}
.mini-editor__placeholder {
	color: `#bfbfbf;`
	line-height: 30px;
	cursor: text;
}


### /* Ослабление резкости границы меню профиля, в шапке  (цвет, яркость, толщина) */
Было:
![изображение](https://user-images.githubusercontent.com/67212103/121442886-2996f080-c995-11eb-9fc3-1bc036e0052f.png)
Стало:
![изображение](https://user-images.githubusercontent.com/67212103/121442898-2f8cd180-c995-11eb-9b07-19c1c9b318db.png)

.subsites_tune_widget_mobile, .list-editable__item, .ui-button--11, .new_entries__counter, .club_dummy__button--pay, .bubble, .bubble[arrow-alignment^="top"]::before, .navigationDropdown__menu--shown, .herzen__command_list, .search-dropdown, .push_offer__content, .block-special-button a, .vue-slider-dot-handle, .ui-limited-input::after, .attacher .ui-button, .v-create-button__dropdown, .v-split-button__dropdown {
	border: `2px solid #a3daee82;`
}


### /* Доработка цвета врезок-ссылок на другие статьи, в тексте записи */
Было (в покое):
![изображение](https://user-images.githubusercontent.com/67212103/121443831-edfd2600-c996-11eb-810e-fe7ca165750c.png)
Стало (в покое):
![изображение](https://user-images.githubusercontent.com/67212103/121443847-f3f30700-c996-11eb-9209-4b6de08d4a46.png)

Было (при наведении курсора):
![изображение](https://user-images.githubusercontent.com/67212103/121444040-5c41e880-c997-11eb-928f-cba96112c6d3.png)
Стало (при наведении курсора):
![изображение](https://user-images.githubusercontent.com/67212103/121444043-606e0600-c997-11eb-9a96-37f5181b3df1.png)

.audio, .island--vacancies_entry, .island--vacancies_recent, .google_search_wrapper .gsc-cursor-box, .form2__field--select .dropdown2, .form2__field--suggest .dropdown2, .form2__field--image .image, .vacancy_edit__mode, .ui_sub_menu--bordered, .ui_sub_menu--shown .ui_sub_menu--bordered::before, .editor__author .dropdown__found__list, .editor__header-select .dropdown__found__list, .comments_updates, .shares_popup, .shares_popup::before, .page--subsite .subsite__user__avatar, .andropov_preview--image, .ui_modal_window__footer, .form2__field--select .dropdown2__found, .form2__field--suggest .dropdown2__found, .b-article .image-wrapper-2--with_border, .comments_form__possessed .possessed_user_list, .subsites_catalog__label--bordered, .page--search .search_results__header, .subsite_card_short_with_content, .subsite_card_short_with_content__content, .status_panel--state-archived, .company_card, .subsites_tune__header, .ui_tabs--with_border, .head-notifies__header, .notification:not(:last-of-type), .head-notifies__footer, .live__item--comment, .ui-feed-header, .best_entries--entry, .page--subsite .subsite__settings__section, .subsites_tune__panel, .best_comments__header, .live, .sidebar, .ui-border--top, .subsites_catalog__search, .subsite_settings__section, .vb-content, .hljs, .content-image--with_border > div, .block-audio, .block-code, .u-notification--border, .ui_modal_window__header--border, .messenger-panel__down-head, .messenger-panel__down-footer, .content-header-note, .aside__header, .aside, .chat-header, .chat-bottom-actions, .chat-form, .message--selected .message__actions-select, .chat-bottom-actions__right-button, .messenger-panel .channel-item__info, .vote .vote__users .icon, .vote .vote__users, .yap-inventory__item::before, .yap-keeper-popup__bubble, .igrozhur-sidebar__container, .igrozhur-sidebar__button, .reposters_list, .attacher__form, .form2__field--advanced_list .text__input, .form2__field--advanced_list .advanced_list__list, .form2__field--sticky, .v-table__row:not(:last-child), .chat-info__bottom, .chat__header, .table__row:not(:last-child):not(.table__row--header), .andropov_link, .ui-border--bottom, .select__current {
	border-color: `#3c3c3c` !important;
}

.andropov_link {
	display: block;
	padding: 11px 16px;
	border: `3px solid #3c3c3c` !important;
	border-radius: 4px;
	color: #000 !important;
	max-width: 600px;
	`background-color: #3c3c3c;`
}
}

/**/

**Comment by 333hronos** [comment]
Вопрос:
А лишние строки которые не правил можно удалить?
Они скопировались вместе с исправленными, когда я нажимал "Скопировать правило" в инспекторе разметки.

Правильно понимаю, что в коде тем оформления для Stylus главное - это заголовок элемента, и конкретная измененная в нем строка?

**Comment by neko-natum** [comment]
Можешь эти изменения как pull request сделать чтобы я просто вытянул их в основу? А то сейчас нет средств нормально внести их и оттеснить.

**Comment by neko-natum** [comment]
Смерджил, но немного пофиксил. В настройках стиля выключи золотой цвет брендирования и будет предложенный новый цвет. Просто я один раз поставил по дефолту синий и мне несколько человек написало в личку типа вертай обратно.

**Comment by 333hronos** [comment]
Спасибо, все обновилось. Да, я как макака, там что-то понаписал)

Ничего, тогда серый логотип DTF я своим доп. стилем просто переведу в бренд-цвет, и все будут счастливы :)
