### ISSUE TITLE
Некорректное отображение ленты комментариев на странице

### ISSUE THREAD

**Issue by Mef45** [neko-natum/DTF-dark-themes#4]
Сначала подумал что фон пропал, потом вспомнил что фона там нет и был изменен цвет текста ( ._.)

![image](https://user-images.githubusercontent.com/26562037/124213305-c6b6f600-db09-11eb-9767-05da265966ef.png)

**Comment by neko-natum** [comment]
Названия классов блоков стали рандомно-генерируемыми и их поддержка теперь невозможна. Так что теперь только остаётся ждать когда всё сломается.
